### ISSUE TITLE
Bulk injection of messages

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-td#10]
@lilitkarapetyan - I'm keen to learn about how the browser (& PouchDb) handles large numbers of messages (including when the browser connects to an existing database).

So, could you implement the buttons to inject high numbers of messages?
https://docs.google.com/presentation/d/1KqBWPbsBpz6ZKkH44q_DVRfVHm4nUIcjDVbg8ThYhks/edit#slide=id.g4cd0e00987_0_77

I suggest you randomly cycle through the message types, and randomly cycle through the from/to combinations

**Comment by IanMayo** [comment]
@lilitkarapetyan - instead of `Generate messages`, could you implement  `Generate 50 messages` , `Generate 100 messages` and `Generate 1000` messages?

Or - you could pull out the `Generate messages` into a label, then the buttons are just 50, 100,1000.

**Comment by lilitkarapetyan** [comment]
done
