### ISSUE TITLE
Switch from red/blue to red/blue/white

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-td#12]
The two chat rooms at the top are Red/Blue.

We're going to introduce a third color: White.  White is the color for "Game control" at the bottom.

So, red and blue will only ever communicate with white.  That means we can pre-fill from/to in the Red/Blue chat room forms.

White could communicate with red or blue.  So in Game Control, we will pre-fill the `From`, but leave the "to" empty.

**Comment by lilitkarapetyan** [comment]
white chat added. 
If you need you can add new chat or change colors or options
https://github.com/serge-web/serge-td/tree/master/src/defaults
 
now game control "from" pre-fill value is white,
"to" field by default on first item [red or blue], should I remove select and put a input field?

**Comment by IanMayo** [comment]
No, it's right that "to" is a drop-down.

The Game Designer will decide which other players this player can talk to.  So, we'll put those values in the drop-down.
