### ISSUE TITLE
Display form editor as "grid"

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-td#15]
The form editor takes up a lot of space:
![image](https://user-images.githubusercontent.com/1108513/53183794-e661b980-35f3-11e9-8fcb-df7d47c08eff.png)

But, if we set "format" as "grid" in the schema, it's more compact:
![image](https://user-images.githubusercontent.com/1108513/53184040-46f0f680-35f4-11e9-9eeb-df2d762b2037.png)

I would change it myself, but I keep getting denied, grr.

So, we just need to add the new property to the schema:
![image](https://user-images.githubusercontent.com/1108513/53183901-098c6900-35f4-11e9-90d6-18467f226213.png)

![image](https://user-images.githubusercontent.com/1108513/53183981-2e80dc00-35f4-11e9-9393-ca50b196065c.png)

**Comment by lilitkarapetyan** [comment]
For chat add form used default format.
For game control it's updated to a grid
